# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDEyYTQ2NzRmZGE0M2I3ZTRmYjZmNzFlYWRhYjU2Y2E3YzkwOTYzNGRmNTNkYTc0NzJhYmMzMDczN2Q5M2Y5ODhjN2UxMGViNWMwMDMyNDJlZmMyZmE4MGFiNWNhNGIwYmQ1OGM2YTE1YmFmZTU1ODAzNDc1MzE1ZjQ3YTI2MTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
